### DISCUSSION TITLE
Strange hvac_action status of thermostat component

### DISCUSSION THREAD

**Discussion by heinemannj** [nliaudat/floor-heating-controller#10] [General]
Strange hvac_action status of thermostat component:

![image](https://github.com/nliaudat/floor-heating-controller/assets/3251642/34a3e765-7d3b-43d8-a196-20930079efb7)
![image](https://github.com/nliaudat/floor-heating-controller/assets/3251642/6b291d6f-6f2c-4918-bd9a-6d68edf85776)

```
climate:  
  - platform: thermostat
    id: ${ch1_id}_return_flow_thermostat
    name: ${ch1_name}_return_flow-thermostat
    sensor: ${ch1_id}_return_flow
    default_preset: default
    on_boot_restore_from: memory
    startup_delay: true
    preset:
      - name: default
        default_target_temperature_low: ${ch1_return_flow_default_target_temperature_low}
        default_target_temperature_high: ${ch1_return_flow_default_target_temperature_high}
        mode: HEAT
    min_cooling_off_time: 300s
    min_cooling_run_time: 300s
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    heat_action: 
         - lambda: 'return;' # do nothing cause action is triggered by time interval
    cool_action:
         - lambda: 'return;'
    idle_action:
         - lambda: 'return;' 
    visual:
      min_temperature: ${heating_inside_norm}
      max_temperature: ${heating_circuit_supply_flow_norm}
      temperature_step: 0.1 °C
```

**Comment by nliaudat** [comment]
Your target are between 23.0 and 23.5°. The formula takes mean aka 23.25° for target. 
Current temp is 23.4° and is in range. 
What's the problem ?

**Comment by heinemannj** [comment]
I've found the solution for use cases if the `desired set point minimun integral` is different then the default of "0.5".

You have to modify:
```
    set_point_minimum_differential: 0.4
    heat_deadband: 0.2°C
    heat_overrun: 0.2°C
```

![image](https://github.com/nliaudat/floor-heating-controller/assets/3251642/a19dc236-e50f-4fa2-9eab-35bb87b26790)

```
climate:
  - platform: thermostat
    id: ${ch1_id}_return_flow_thermostat
    name: ${ch1_name}_return_flow-thermostat
    sensor: ${ch1_id}_return_flow
    default_preset: COMFORT
    on_boot_restore_from: memory
    startup_delay: true
    preset:
      - name: ECO
        default_target_temperature_low: ${ch1_return_flow_default_target_temperature_low}
        default_target_temperature_high: ${ch1_return_flow_default_target_temperature_high}
        mode: HEAT
      - name: COMFORT
        default_target_temperature_low: ${ch1_return_flow_default_target_temperature_low}
        default_target_temperature_high: ${ch1_return_flow_default_target_temperature_high}
        mode: HEAT
    min_cooling_off_time: 300s
    min_cooling_run_time: 300s
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    set_point_minimum_differential: 0.4
    heat_deadband: 0.2°C
    heat_overrun: 0.2°C
    heat_action: 
         - lambda: 'return;' # do nothing cause action is triggered by time interval
    cool_action:
         - lambda: 'return;'
    idle_action:
         - lambda: 'return;' 
    visual:
      min_temperature: ${heating_inside_eco}
      max_temperature: ${heating_circuit_supply_flow_norm}
      temperature_step: 0.1 °C
```
