### DISCUSSION TITLE
Replacement of endstop cover with feedback cover

### DISCUSSION THREAD

**Discussion by heinemannj** [nliaudat/floor-heating-controller#12] [Ideas]
Has anybody already tested the  feedback cover platform?

https://esphome.io/components/cover/feedback

`The feedback cover platform allows you to create covers with position control that can optionally have feedback from sensors to detect the fully-open and fully-closed states (endstops), and from sensors to detect actual movement (opening/closing).`

My basic understand for the difference between endstop cover and feedback cover:

- All functionality of the endstop cover
- Capability the dectect real movement

`If movement feedback is available, the cover no longer operates in optimistic mode (assuming that movement starts as soon as an action is triggered) and can also react to commands issued to cover from an external control and still keep states in sync (useful for “smartization” of an existing cover).`

**Comment by nliaudat** [comment]
Never tested. 

I have a tried current_based cover (which I mean is the main source of feedback cover) : 

```
cover:
  - platform: current_based
    name: "Current Based Cover"
    open_sensor: BEMF_1_sensor_ADC
    open_moving_current_threshold: 0.05
    open_obstacle_current_threshold: 0.25
    open_duration: 40s
    open_action:
      - switch.turn_on: CH1_IB_pin
    close_sensor: BEMF_1_sensor_ADC
    close_moving_current_threshold: 0.05
    close_obstacle_current_threshold: 0.25
    close_duration: 55s
    close_action:
      - switch.turn_on: CH1_IA_pin
    stop_action:
      - switch.turn_off: CH1_IA_pin
      - switch.turn_off: CH1_IB_pin

    obstacle_rollback: 1%
    malfunction_detection: False
    start_sensing_delay: 0.8s
    id: CH1_cover_current_based
```

**The main problem is that threshold are hardcoded and cannot be changed after firmware upload**
