### DISCUSSION TITLE
Refactored as "packages as tempate"

### DISCUSSION THREAD

**Discussion by nliaudat** [nliaudat/floor-heating-controller#13] [Announcements]
Configuration and coding is much simpler as using the [package as template](https://esphome.io/guides/configuration-types.html#packages-as-templates))

Many files have been deleted and packaged in heating_channel.yaml

The configuration is done with packages in config.yaml:
```
  channel_1: !include
    file: heating_channel.yaml
    vars:
      channel_number: 1
      id: wc
      frendly_name: wc
      temperature_sensor: corridor_temperature_sensor
      default_target_temperature_low: "19 °C"
      default_target_temperature_high: "20 °C"

  channel_2: !include
    file: heating_channel.yaml
    vars:
      channel_number: 2
      id: storage
      frendly_name: storage
      temperature_sensor: reduit_temperature_sensor
      default_target_temperature_low: "21 °C"
      default_target_temperature_high: "21 °C"

```
