### DISCUSSION TITLE
Minimum opening of the valve

### DISCUSSION THREAD

**Discussion by patti9000** [nliaudat/floor-heating-controller#16] [General]
Is there a possibility for configuring an minimum opening for each valve? 
Why? Well, in my case im living in a flat an we don't have to heat that much. The result of that, is that our floors are cold most of the time. The Homematic IP FALMOT (in combination with RaspberryMatic) lacks this feature and this is why I'm looking for different options.
Thanks

**Comment by nliaudat** [comment]
Hi, 

It's not a buildin function, but you have full access to the code and can make everything you want. 

Perhaps, the better way to go is to modify 

https://github.com/nliaudat/floor-heating-controller/blob/5149efdfb095ab88c942dc75e6529c23844dafd9/heating_channel_linear.yaml#L143

and adding : 

if (target_position <id(min_valve_pos).state) { target_position = id(min_valve_pos).state;} 

with a value you set in [inputs.yaml](https://github.com/nliaudat/floor-heating-controller/blob/main/inputs.yaml)

```
number:
   
  - platform: template
    name: "min valve position"
    optimistic: true
    min_value: 0
    max_value: 100
    step: 1
    restore_value: true
    initial_value: 5
    id: min_valve_pos
```

You have to understand in low temperature floor heating, if the foor is at 28°, you are heating at the max power and the valves are full open. 
This will result in the room getting hot. 

That's why nobody make that kind of implementation. 

If you have already a controller, you can play with the target temperature to find you area of confort before changing the system. 

Regards
