### DISCUSSION TITLE
pid doesnt work correct?

### DISCUSSION THREAD

**Discussion by grericht** [nliaudat/floor-heating-controller#18] [Q&A]
after using tanh same days i try to test pid. but first of all: i hat to add climate_id: PID_CH${channel_number} 4times and change default_target_temperature:_low to default_target_temperature

```
climate:
  - platform: pid
    name: ${frendly_name}
    id: PID_CH${channel_number}
    sensor: ${temperature_sensor}
    default_target_temperature: ${default_target_temperature}
```

```
sensor:
  - platform: pid
    name: "PID ${frendly_name} RESULT"
    id: PID_CH${channel_number}_result
    climate_id: PID_CH${channel_number}
    type: RESULT
    
  - platform: pid
    name: "PID ${frendly_name} KP"
    id: PID_CH${channel_number}_kp
    climate_id: PID_CH${channel_number}
    type: KP
    
  - platform: pid
    name: "PID ${frendly_name} KI"
    id: PID_CH${channel_number}_ki
    climate_id: PID_CH${channel_number}
    type: KI
    
  - platform: pid
    name: "PID ${frendly_name} KD"
    id: PID_CH${channel_number}_kd
    climate_id: PID_CH${channel_number}
    type: KD
```

but now it seems to resarts every 5 seconds
