### DISCUSSION TITLE
BEMF value changes in regular intervals

### DISCUSSION THREAD

**Discussion by flexmatics** [nliaudat/floor-heating-controller#4] [Q&A] [answered]
Hi,

I've previously started thread in wrong place [here](https://github.com/nliaudat/esp32_8ch_motor_shield/discussions/29). This is to continue on this topic, as couldn't resolve yet.

Problem is that at roughly 20 mins intervals, I get spike of BEMF value on random channel (this is observed on my both boards that I have on 1st/2nd floor). Actuator itself does not seem to be affected (i.e. there is no opening/closing physically). Spikes are up to ~0.4 V. Typically, only single channel on the same board is affected at the same time (but it is random). Any ideas what could I try to resolve, or maybe some other logs should be provided to understand the issue?

Here is how it looks like in HA:
![image](https://user-images.githubusercontent.com/79056776/204139001-e755cd55-7bb0-45e8-b1d1-cc578bd447bc.png)

**Comment by nliaudat** [comment]
Please try to change interval in time.yaml for BEMF2 (channel 3 & 4) to see if it's related to motor move

like this : 
```
interval:
  - interval: 1min
    then:
      - script.execute: TH3_check
  - interval: 5min
    then:
      - script.execute: TH4_check
  - interval: 15min
    then:
      - script.execute: TH1_check
      - script.execute: TH5_check
  - interval: 17min
    then:
      - script.execute: TH2_check
      - script.execute: TH6_check
  - interval: 19min
    then:
     # - script.execute: TH3_check
      - script.execute: TH7_check
  - interval: 21min
    then:
     # - script.execute: TH4_check
      - script.execute: TH8_check
```
