### DISCUSSION TITLE
Cover Calibration script

### DISCUSSION THREAD

**Discussion by heinemannj** [nliaudat/floor-heating-controller#9] [General]
Origional code:

```
script:

  - id: calibrate_CH1_cover
    then:
      - logger.log: "Calibrate CH1_cover"
      - cover.close: CH1_cover
      - delay: 5s
      - cover.open: CH1_cover
      - delay: 5s
      - cover.close: CH1_cover
      - delay: 5s
      - cover.open: CH1_cover
      - delay: 5s
      - cover.close: CH1_cover
      - delay: 5s
      - cover.open: CH1_cover
      - delay: 60s
      - cover.close: CH1_cover
      - delay: 60s
      - cover.close: CH1_cover
      - delay: 60s
      - cover.close: CH1_cover
```

Can somebody please explain in which way above calibration is working and why nine different tests are required?

My basic understanding is like the following:

```
      - cover.open: CH1_cover
      - delay: 60s # max_duration of the cover => cover should be completely open
      - cover.close: CH1_cover
      - delay: 60s # max_duration of the cover  => cover should be completely closed
      - cover.open: CH1_cover
      - delay: 60s # max_duration of the cover => cover should be completely open
```
