### ISSUE TITLE
Documentation: Connect 1-Wire bus with DS18B20 temperature sensors

### ISSUE THREAD

**Issue by heinemannj** [nliaudat/floor-heating-controller#6]
Other temperature sensor sample:
https://github.com/nliaudat/floor-heating-controller/blob/main/sensor_temperature.yaml

```
# Connect 1-Wire bus with DS18B20 temperature sensors
#

dallas:
  - pin: GPI22
    update_interval: 15s

sensor:
  - platform: dallas
    address: 0x8b031760522cff28
    name: "301_Heizkreis-WC-Vorlauf"
    id: WC_Vorlauf
    resolution: 12
    accuracy_decimals: 2
    filters:
      - offset: 0.0

  - platform: dallas
    address: 0x353c38f649a51b28
    name: "301_Heizkreis-WC-Ruecklauf"
    id: WC_Ruecklauf
    resolution: 12
    accuracy_decimals: 2
    filters:
      - offset: 0.0

```
